name: midterm
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.19.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  url_launcher: ^6.2.5
  flutter_dotenv: ^5.1.0
  sqflite: ^2.3.0
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  flutter_signin_button: ^2.0.0
  oauth2: ^2.0.3
  cloud_firestore: ^5.6.7
  provider: ^6.0.5
  carousel_slider: ^5.0.0
  lottie: ^3.3.1
  animate_do: ^2.1.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/products/
    - assets/logo.png
    - assets/animations/loading.json

# ðŸ‘‡ Ð’ÐÐ• Ð±Ð»Ð¾ÐºÐ° flutter!
localization:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
